name: ruff tests

on:
  push:
  pull_request:

jobs:
  linting_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run check
        uses: chartboost/ruff-action@v1
        with:
            version: 0.6.3
      - name: Run format 
        uses: chartboost/ruff-action@v1
        with:
            args: 'format --check'
            version: 0.6.3
